#!/bin/zsh
# =============================================================================
# install-controller.sh
# Deploys and starts the Liberty Collective Controller from the golden package.
#
# Usage:  scripts/install-controller.sh
#
# What it does:
#   1. Verifies the golden package exists
#   2. Cleans any previous controller install
#   3. Unpacks the package into installs/controller/
#   4. Renames the server from template-26.0.0.8 → controller
#   5. Drops in configDropins/overrides (role + ports)
#   6. Writes bootstrap.properties
#   7. Runs collective create (initialises collective PKI)
#   8. Starts the controller
#   9. Waits for it to be ready and verifies Admin Center
# =============================================================================

SCRIPT_DIR="${0:A:h}"
source "${SCRIPT_DIR}/00-set-env.sh"

PACKAGE="${WORKSPACE_ROOT}/packages/liberty-package-26.0.0.8.zip"
INSTALL_DIR="${WORKSPACE_ROOT}/installs/controller"
SERVER_DIR="${INSTALL_DIR}/wlp/usr/servers/controller"
WLP_BIN="${INSTALL_DIR}/wlp/bin/server"
OVERRIDES_DIR="${SERVER_DIR}/configDropins/overrides"
CONFIG_SRC="${WORKSPACE_ROOT}/config/controller"

CONTROLLER_HTTP=9080
CONTROLLER_HTTPS=9443
KEYSTORE_PASS="Liberty26ctrl!"
ADMIN_PASS="admin"
COLLECTIVE_PASS="Liberty26ctrl!"

echo ""
echo "=== Liberty Collective Controller — Install ==="
echo ""

# ---------------------------------------------------------------------------
# 1. Verify package exists
# ---------------------------------------------------------------------------
echo "[1/9] Checking golden package..."
if [[ ! -f "${PACKAGE}" ]]; then
    echo "  ERROR: Package not found: ${PACKAGE}"
    echo "  Run scripts/03-build-package.sh first."
    exit 1
fi
echo "      Found: ${PACKAGE}"
echo ""

# ---------------------------------------------------------------------------
# 2. Clean previous install
# ---------------------------------------------------------------------------
echo "[2/9] Cleaning previous controller install..."
rm -rf "${INSTALL_DIR}"
mkdir -p "${INSTALL_DIR}"
echo "      Clean"
echo ""

# ---------------------------------------------------------------------------
# 3. Unpack package
# ---------------------------------------------------------------------------
echo "[3/9] Unpacking package..."
unzip -q "${PACKAGE}" -d "${INSTALL_DIR}"
echo "      Unpacked to ${INSTALL_DIR}"
echo ""

# ---------------------------------------------------------------------------
# 4. Rename server template-26.0.0.8 → controller
# ---------------------------------------------------------------------------
echo "[4/9] Renaming server to 'controller'..."
TEMPLATE_DIR="${INSTALL_DIR}/wlp/usr/servers/template-26.0.0.8"
if [[ ! -d "${TEMPLATE_DIR}" ]]; then
    echo "  ERROR: Expected template directory not found: ${TEMPLATE_DIR}"
    exit 1
fi
mv "${TEMPLATE_DIR}" "${SERVER_DIR}"
echo "      Renamed → ${SERVER_DIR}"
echo ""

# ---------------------------------------------------------------------------
# 5. Drop in configDropins/overrides
# ---------------------------------------------------------------------------
echo "[5/9] Applying configDropins overrides..."
mkdir -p "${OVERRIDES_DIR}"
cp "${CONFIG_SRC}/role-override.xml"  "${OVERRIDES_DIR}/role-override.xml"
cp "${CONFIG_SRC}/ports-override.xml" "${OVERRIDES_DIR}/ports-override.xml"
echo "      role-override.xml  → collectiveController + adminCenter-1.0"
echo "      ports-override.xml → HTTP ${CONTROLLER_HTTP} / HTTPS ${CONTROLLER_HTTPS}"
echo ""

# ---------------------------------------------------------------------------
# 6. Write bootstrap.properties
# ---------------------------------------------------------------------------
echo "[6/9] Writing bootstrap.properties..."
cat > "${SERVER_DIR}/bootstrap.properties" <<EOF
# Controller bootstrap properties — generated by install-controller.sh
default.http.port=${CONTROLLER_HTTP}
default.https.port=${CONTROLLER_HTTPS}
keystore.password=${KEYSTORE_PASS}
admin.password=${ADMIN_PASS}
EOF
echo "      Written"
echo ""

# ---------------------------------------------------------------------------
# 7. Run collective create (initialises collective PKI)
#    Must use the instance's own wlp/bin/collective — not the build-phase binary
# ---------------------------------------------------------------------------
echo "[7/9] Initialising collective PKI (collective create)..."
"${INSTALL_DIR}/wlp/bin/collective" create controller \
    --keystorePassword="${KEYSTORE_PASS}" \
    --hostName=localhost \
    --createConfigFile="${OVERRIDES_DIR}/collective-create.xml" 2>&1 | tail -5

if [[ $? -ne 0 ]]; then
    echo "  ERROR: collective create failed."
    echo "  Check: ${SERVER_DIR}/logs/messages.log"
    exit 1
fi

# collective create writes an empty quickStartSecurity placeholder — fill it in
# so the admin user is available for collective join and Admin Center login
sed -i '' "s|quickStartSecurity userName=\"\" userPassword=\"\"|quickStartSecurity userName=\"admin\" userPassword=\"${ADMIN_PASS}\"|" \
    "${OVERRIDES_DIR}/collective-create.xml"
echo "      PKI initialised + quickStartSecurity configured (admin/${ADMIN_PASS})"
echo ""

# ---------------------------------------------------------------------------
# 8. Start the controller
# ---------------------------------------------------------------------------
echo "[8/9] Starting controller..."
"${WLP_BIN}" start controller

if [[ $? -ne 0 ]]; then
    echo "  ERROR: Controller failed to start."
    echo "  Check: ${SERVER_DIR}/logs/messages.log"
    exit 1
fi
echo ""

# ---------------------------------------------------------------------------
# 9. Wait for ready and verify
# ---------------------------------------------------------------------------
echo "[9/9] Waiting for controller to be ready..."
MAX_WAIT=60
WAITED=0
while [[ ${WAITED} -lt ${MAX_WAIT} ]]; do
    if grep -q "server is ready" "${SERVER_DIR}/logs/messages.log" 2>/dev/null; then
        break
    fi
    sleep 2
    (( WAITED += 2 ))
    echo "      Waiting... (${WAITED}s)"
done

if [[ ${WAITED} -ge ${MAX_WAIT} ]]; then
    echo "  WARNING: Timed out waiting for ready message. Check messages.log."
fi

# Verify Admin Center
CODE=$(curl -k -s -o /dev/null -w "%{http_code}" https://localhost:${CONTROLLER_HTTPS}/adminCenter 2>/dev/null)
if [[ "${CODE}" == "200" || "${CODE}" == "302" ]]; then
    echo "      Admin Center: READY (HTTP ${CODE})"
else
    echo "      WARNING: Admin Center returned HTTP ${CODE} — may still be starting"
fi

echo ""
echo "=== Controller install complete ==="
echo ""
echo "  Admin Center:  https://localhost:${CONTROLLER_HTTPS}/adminCenter"
echo "  Credentials:   admin / ${ADMIN_PASS}"
echo ""
