#!/bin/bash
# =============================================================================
# install-ihs.sh
# Cleans any previous IHS install, installs IBM HTTP Server from the
# pre-provisioned ARCHIVE ZIP, installs the WAS plugin, writes a baseline
# httpd.conf and the apachectl wrapper.
#
# Usage:
#   scripts/install-ihs.sh
#
#   After install, reload PATH in your current terminal:
#   source ~/.bashrc
#
# Overrides:
#   IHS_INSTALLER_DIR   directory that contains the IHS ZIP  (default below)
#   IHS_INSTALL_ROOT    where IHS is installed               (default below)
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/00-set-env.sh"

IHS_INSTALL_ROOT="${IHS_INSTALL_ROOT:-/home/itzuser/IBM/HTTPServer}"
IHS_INSTALLER_DIR="${IHS_INSTALLER_DIR:-/home/itzuser/software/IHS}"
IHS_STAGING="${WORKSPACE_ROOT}/_ihs_staging"
IHS_LIB="${IHS_INSTALL_ROOT}/lib"
HTTPD_BIN="${IHS_INSTALL_ROOT}/bin/httpd"
APACHECTL="${IHS_INSTALL_ROOT}/bin/apachectl"
HTTPD_CONF="${IHS_INSTALL_ROOT}/conf/httpd.conf"

echo ""
echo "=== IBM HTTP Server — Install ==="
echo ""

# ---------------------------------------------------------------------------
# 1. Clean previous install
# ---------------------------------------------------------------------------
if [[ -d "${IHS_INSTALL_ROOT}" ]]; then
    echo "[1/5] Removing previous install at ${IHS_INSTALL_ROOT}..."
    rm -rf "${IHS_INSTALL_ROOT}"
fi

# ---------------------------------------------------------------------------
# 2. Locate and extract the installer ZIP
# ---------------------------------------------------------------------------
echo "[2/5] Installing IHS..."

if [[ ! -d "${IHS_INSTALLER_DIR}" ]]; then
    echo "  ERROR: Installer directory not found: ${IHS_INSTALLER_DIR}" >&2
    echo "         Set IHS_INSTALLER_DIR to the directory containing the IHS ZIP." >&2
    exit 1
fi

IHS_ZIP=$(find "${IHS_INSTALLER_DIR}" -maxdepth 2 -name "*.zip" | head -1)
if [[ -z "${IHS_ZIP}" ]]; then
    echo "  ERROR: No ZIP file found in ${IHS_INSTALLER_DIR}" >&2
    exit 1
fi
echo "      ZIP: ${IHS_ZIP}"

rm -rf "${IHS_STAGING}"
mkdir -p "${IHS_STAGING}"
unzip -q "${IHS_ZIP}" -d "${IHS_STAGING}"

# Find the top-level subdirectory that contains a bin/ — that is the IHS tree
ARCHIVE_DIR=""
for dir in "${IHS_STAGING}"/*/; do
    if [[ -d "${dir}bin" ]]; then
        ARCHIVE_DIR="${dir%/}"
        break
    fi
done

if [[ -z "${ARCHIVE_DIR}" ]]; then
    echo "  ERROR: Could not find IHS directory inside ZIP." >&2
    rm -rf "${IHS_STAGING}"
    exit 1
fi

mkdir -p "$(dirname "${IHS_INSTALL_ROOT}")"
mv "${ARCHIVE_DIR}" "${IHS_INSTALL_ROOT}"
rm -rf "${IHS_STAGING}"
echo "      Installed to ${IHS_INSTALL_ROOT}"

# ---------------------------------------------------------------------------
# 3. Install WAS plugin (mod_was_ap24_http.so)
# ---------------------------------------------------------------------------
echo "[3/5] Installing WAS plugin..."

WAS_PLUGIN_SRC=$(find "${IHS_INSTALLER_DIR}" -name "mod_was_ap24_http.so" 2>/dev/null | head -1)

if [[ -n "${WAS_PLUGIN_SRC}" ]]; then
    cp "${WAS_PLUGIN_SRC}" "${IHS_INSTALL_ROOT}/modules/mod_was_ap24_http.so"
else
    PLUGIN_ENTRY=$(unzip -l "${IHS_ZIP}" 2>/dev/null | grep "mod_was_ap24_http.so" | awk '{print $NF}' | head -1)
    if [[ -n "${PLUGIN_ENTRY}" ]]; then
        unzip -q -j "${IHS_ZIP}" "${PLUGIN_ENTRY}" -d "${IHS_INSTALL_ROOT}/modules/"
    else
        echo "  WARNING: mod_was_ap24_http.so not found — plugin not installed." >&2
    fi
fi
echo "      ${IHS_INSTALL_ROOT}/modules/mod_was_ap24_http.so"

# ---------------------------------------------------------------------------
# 4. Write baseline httpd.conf + required directories
#    The ARCHIVE ZIP does not ship a conf file. We create a minimal working
#    configuration that loads the WAS plugin and is ready for step1-was-plugin.sh.
# ---------------------------------------------------------------------------
echo "[4/5] Writing baseline httpd.conf..."

mkdir -p "${IHS_INSTALL_ROOT}/conf" \
         "${IHS_INSTALL_ROOT}/logs" \
         "${IHS_INSTALL_ROOT}/htdocs"

cat > "${HTTPD_CONF}" <<CONF_EOF
# =============================================================================
# IBM HTTP Server — baseline configuration
# Generated by install-ihs.sh — safe to re-generate via scripts/reset-ihs.sh
# =============================================================================
ServerRoot "${IHS_INSTALL_ROOT}"
Listen 8080
ServerName localhost:8080
ServerAdmin admin@localhost

LoadModule mpm_worker_module      modules/mod_mpm_worker.so
LoadModule authz_core_module      modules/mod_authz_core.so
LoadModule log_config_module      modules/mod_log_config.so
LoadModule unixd_module           modules/mod_unixd.so
LoadModule dir_module             modules/mod_dir.so
LoadModule mime_module            modules/mod_mime.so

# WAS plugin — activated by scripts/step1-was-plugin.sh
LoadModule was_ap24_module        modules/mod_was_ap24_http.so

User itzuser
Group itzuser

DocumentRoot "${IHS_INSTALL_ROOT}/htdocs"
<Directory "${IHS_INSTALL_ROOT}/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

ErrorLog  "logs/error_log"
LogLevel  warn
LogFormat "%h %l %u %t \"%r\" %>s %b" common
CustomLog "logs/access_log" common

TypesConfig conf/mime.types
CONF_EOF

cat > "${IHS_INSTALL_ROOT}/conf/mime.types" <<'MIME_EOF'
text/html  html htm
text/plain txt
application/octet-stream bin
MIME_EOF

echo "<html><body><h1>IBM HTTP Server</h1></body></html>" \
    > "${IHS_INSTALL_ROOT}/htdocs/index.html"

echo "      Written: ${HTTPD_CONF}"

# ---------------------------------------------------------------------------
# 5. Write apachectl wrapper + add IHS bin to PATH
#    The ARCHIVE format ships only httpd. This wrapper sets LD_LIBRARY_PATH
#    so IHS finds its bundled libapr and passes -f <conf> so httpd never
#    falls back to its compiled-in default path.
# ---------------------------------------------------------------------------
echo "[5/5] Writing apachectl wrapper..."
cat > "${APACHECTL}" <<WRAPPER_EOF
#!/bin/bash
# IHS apachectl — generated by install-ihs.sh
export LD_LIBRARY_PATH="${IHS_LIB}\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
HTTPD="${HTTPD_BIN}"
CONF="${HTTPD_CONF}"
case "\$1" in
    start|stop|restart|graceful) exec "\${HTTPD}" -f "\${CONF}" -k "\$1" ;;
    configtest)                  exec "\${HTTPD}" -f "\${CONF}" -t ;;
    -v|-V)                       exec "\${HTTPD}" "\$@" ;;
    *)                           exec "\${HTTPD}" -f "\${CONF}" "\$@" ;;
esac
WRAPPER_EOF
chmod +x "${APACHECTL}"
echo "      Written: ${APACHECTL}"

if ! grep -qF "${IHS_INSTALL_ROOT}/bin" ~/.bashrc; then
    echo "export PATH=\"${IHS_INSTALL_ROOT}/bin:\$PATH\"" >> ~/.bashrc
    echo "      Added IHS bin to ~/.bashrc"
fi

echo ""
echo "=== Done. IHS installed at ${IHS_INSTALL_ROOT} ==="
echo ""
echo "  Reload PATH in your current terminal:"
echo "    source ~/.bashrc"
echo ""
echo "  Then verify:"
echo "    apachectl -v"
echo ""
