#!/bin/bash
# =============================================================================
# step1-was-plugin.sh
# Configures the IHS WAS plugin to route HTTP traffic to ALL running Liberty
# collective members using a static plugin-cfg.xml (Round Robin).
#
# Architecture:
#   Browser → IHS:1080 → mod_was_ap24_http.so → member1:9081 / member2:9082
#                                                / member3:9083 / member4:9084
#
# What this script does:
#   1. Discovers all running member servers (ports 9081–9089)
#   2. Writes plugin-cfg.xml with one <Server> entry per running member
#   3. Adds WebSpherePluginConfig to httpd.conf
#   4. Validates and restarts IHS
#   5. Verifies routing with a test request
# =============================================================================

IHS_ROOT="${IHS_INSTALL_ROOT:-/home/itzuser/usr/IBM/IHS}"
HTTPD_CONF="${IHS_ROOT}/conf/httpd.conf"
PLUGIN_CFG="${IHS_ROOT}/plugin/config/webserver1/plugin-cfg.xml"
APACHECTL="${IHS_ROOT}/bin/apachectl"

echo ""
echo "=== Step 1: Configure WAS plugin — static routing to all running members ==="
echo ""

# ---------------------------------------------------------------------------
# Pre-flight
# ---------------------------------------------------------------------------
if [[ ! -f "${HTTPD_CONF}" ]]; then
    echo "ERROR: httpd.conf not found at ${HTTPD_CONF}"
    echo "       Run scripts/install-ihs.sh first."
    exit 1
fi

if [[ ! -f "${IHS_ROOT}/modules/mod_was_ap24_http.so" && ! -f "${IHS_ROOT}/plugin/bin/64bits/mod_was_ap24_http.so" ]]; then
    echo "ERROR: mod_was_ap24_http.so not found."
    echo "       Run scripts/install-ihs.sh first."
    exit 1
fi

# ---------------------------------------------------------------------------
# 1. Discover all running member servers (ports 9081-9089)
# ---------------------------------------------------------------------------
echo "[1/4] Discovering running member servers..."

declare -a MEMBER_NAMES
declare -a MEMBER_PORTS

for i in 1 2 3 4 5 6 7 8 9; do
    port=$(( 9080 + i ))
    if ss -tlnp 2>/dev/null | grep -q ":${port} "; then
        MEMBER_NAMES+=("member${i}")
        MEMBER_PORTS+=("${port}")
        echo "      member${i} : port ${port} — up"
    fi
done

if [[ ${#MEMBER_NAMES[@]} -eq 0 ]]; then
    echo "ERROR: No member servers found on ports 9081-9089."
    echo "       Run scripts/add-member-26.sh member1 first."
    exit 1
fi
echo "      Total: ${#MEMBER_NAMES[@]} member(s)"
echo ""

# ---------------------------------------------------------------------------
# 2. Write plugin-cfg.xml with one <Server> per running member
# ---------------------------------------------------------------------------
echo "[2/4] Writing ${PLUGIN_CFG}..."

# Build <Server> blocks and <PrimaryServers> list
SERVER_BLOCKS=""
PRIMARY_LIST=""
for idx in "${!MEMBER_NAMES[@]}"; do
    name="${MEMBER_NAMES[$idx]}"
    port="${MEMBER_PORTS[$idx]}"
    SERVER_BLOCKS+="
        <Server CloneID=\"${name}\" ConnectTimeout=\"5\" ExtendedHandshake=\"false\"
                MaxConnections=\"-1\" Name=\"${name}_${port}\"
                ServerIOTimeout=\"900\" WaitForContinue=\"false\">
            <Transport Hostname=\"localhost\" Port=\"${port}\" Protocol=\"http\"/>
        </Server>
"
    PRIMARY_LIST+="            <Server Name=\"${name}_${port}\"/>\n"
done

cat > "${PLUGIN_CFG}" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Liberty WAS Plugin — static Round Robin routing
  Generated by step1-was-plugin.sh on $(date)
  Members: ${MEMBER_NAMES[*]}
-->
<Config ASDisableNagle="false" AcceptAllContent="false"
        AppServerPortPreference="HostHeader" ChunkedResponse="false"
        FIPSEnable="false" IISDisableNagle="false" IISPluginPriority="High"
        IgnoreDNSFailures="false" RefreshInterval="60" ResponseChunkSize="64"
        SSLConsolidatedConfig="false" TrustedProxyEnable="false"
        VHostMatchingCompat="false">

    <Log LogLevel="Error" Name="${IHS_ROOT}/logs/plugin.log"/>

    <Property Name="ESIEnable"                   Value="false"/>
    <Property Name="ESIMaxCacheSize"              Value="1024"/>
    <Property Name="ESIInvalidationMonitor"       Value="false"/>
    <Property Name="ESIEnableRecursiveInclude"    Value="false"/>
    <Property Name="ESIMaxRecursiveIncludeDepth"  Value="10"/>

    <!--
      ServerCluster Name MUST be "defaultCollective" — this is the cluster
      group name that dynamicRouting setup (step 3b) writes into the
      <IntelligentManagement> stanza and uses to identify this collective's
      members at runtime.  The <Route> below must reference the same name
      so the plugin's live routing table is served for the correct route.
    -->
    <ServerCluster CloneSeparatorChange="false" GetDWLMTable="false"
                   IgnoreAffinityRequests="true" LoadBalance="Round Robin"
                   Name="defaultCollective" PostSizeLimit="-1"
                   RemoveSpecialHeaders="true" RetryInterval="60">
${SERVER_BLOCKS}
        <PrimaryServers>
$(printf "${PRIMARY_LIST}")        </PrimaryServers>

    </ServerCluster>

    <UriGroup Name="defaultCollective_URIs">
        <Uri AffinityCookie="JSESSIONID" AffinityURLIdentifier="jsessionid" Name="/*"/>
    </UriGroup>

    <VirtualHostGroup Name="defaultCollective_Hosts">
        <VirtualHost Name="*:1080"/>
    </VirtualHostGroup>

    <Route ServerCluster="defaultCollective"
           UriGroup="defaultCollective_URIs"
           VirtualHostGroup="defaultCollective_Hosts"/>

</Config>
EOF

echo "      Written: ${PLUGIN_CFG}"
echo "      Members included: ${MEMBER_NAMES[*]}"

# ---------------------------------------------------------------------------
# 3. Add WebSpherePluginConfig to httpd.conf (idempotent)
# ---------------------------------------------------------------------------
echo "[3/4] Adding WebSpherePluginConfig to httpd.conf..."

if grep -q "^WebSpherePluginConfig" "${HTTPD_CONF}"; then
    sed -i "s|^WebSpherePluginConfig .*|WebSpherePluginConfig ${PLUGIN_CFG}|" "${HTTPD_CONF}"
    echo "      WebSpherePluginConfig: updated"
else
    echo "" >> "${HTTPD_CONF}"
    echo "# WAS plugin routing — added by step1-was-plugin.sh" >> "${HTTPD_CONF}"
    echo "WebSpherePluginConfig ${PLUGIN_CFG}" >> "${HTTPD_CONF}"
    echo "      WebSpherePluginConfig: added"
fi

RESULT=$("${APACHECTL}" configtest 2>&1)
if echo "${RESULT}" | grep -q "Syntax OK"; then
    echo "      Syntax OK"
else
    echo "ERROR: Config test failed:"
    echo "${RESULT}"
    exit 1
fi

# ---------------------------------------------------------------------------
# 4. (Re)start IHS
# ---------------------------------------------------------------------------
echo "[4/4] Starting IHS..."
# Stop reliably regardless of PID file state — apachectl stop may report
# "not running" if the PID file is missing while the process is still alive.
"${APACHECTL}" stop 2>/dev/null; sleep 2
pkill -9 -f "${IHS_ROOT}/bin/httpd" 2>/dev/null; sleep 1
if ss -tlnp 2>/dev/null | grep -q ":1080 "; then
    echo "ERROR: port 1080 still in use after stop — cannot start IHS"
    ss -tlnp | grep ":1080"
    exit 1
fi
"${APACHECTL}" start
sleep 1

if ! ss -tlnp 2>/dev/null | grep -q ":1080 "; then
    echo "ERROR: IHS failed to start. Check: ${IHS_ROOT}/logs/error_log"
    tail -20 "${IHS_ROOT}/logs/error_log"
    exit 1
fi

echo ""
echo "=== Step 3a complete ==="
echo ""
echo "  Static Round Robin across: ${MEMBER_NAMES[*]}"
echo "  Verify:"
echo "    for i in \$(seq 8); do curl -s http://localhost:1080/server-info/ | grep -o 'member[0-9]*'; done"
echo ""
echo "  IHS plugin log:"
echo "    tail -f ${IHS_ROOT}/logs/plugin.log"
echo ""
echo "  When ready, enable dynamic routing:"
echo "    bash scripts/step2-dynamic-routing.sh"
echo ""
